//Exception Handling Array Out of Bounds Exception Errors
public class Exception_Handling_Example1 {
	public static void main(String[] args) {
// TODO Auto-generated method stub
		System.out.println("Before Exception");
		int arr[] = { 10, 20, 30 };
		System.out.println(arr[4]);
		System.out.println("After Exception");
	}

}
